import os
import sys
import psycopg2
from psycopg2 import OperationalError
from faker import Faker


# get the database connection details from the environment
DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASS = os.getenv('DATABASE_PASS')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PORT = os.getenv('DATABASE_PORT')

try:
    # connect to the database
    conn = psycopg2.connect(
            database=DATABASE_NAME,
            user=DATABASE_USER,
            password=DATABASE_PASS,
            host=DATABASE_HOST,
            port=DATABASE_PORT,
            )
except OperationalError as error:
    print(f"Unable to connect to the database {DATABASE_NAME} on port {DATABASE_PORT}")
    sys.exit(error)

# create a cursor object and get the database version information
cursor = conn.cursor()
cursor.execute("select version()")

# fetch a single row using fetchone() method.
data = cursor.fetchone()
print("Connection established to: ", data)

# drop the employee table
cursor.execute("DROP TABLE IF EXISTS EMPLOYEES")

# create the employee table
sql = '''
    CREATE TABLE EMPLOYEES(
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        FIRST_NAME CHAR(60) NOT NULL,
        LAST_NAME CHAR(60) NOT NULL
    )
'''

cursor.execute(sql)
conn.commit()
print("Table created successfully........")

# generate test data for 100 employees
fake = Faker()

for i in range(0,100):
    first_name = fake.first_name()
    last_name  = fake.last_name()

    sql = f"INSERT INTO EMPLOYEES(id,FIRST_NAME,LAST_NAME) VALUES(DEFAULT,{first_name},{last_name});"
    cursor.execute(sql)
    conn.commit()

# read the data
sql = "SELECT * FROM EMPLOYEES"
cursor.execute(sql)
conn.commit()

# close the connection to the database
conn.close()

